#### Counter - расширяет возможности для решения задач по подсчету предметов

In [16]:
from collections import Counter

In [22]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

c = Counter(cars)

print(c, print(type(c)))

<class 'collections.Counter'>
Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1}) None


##### Операции с Counter 

1) Сложение счетчиков

In [43]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow + counter_spb)

Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})


2) Вычетание счетчиков

In [44]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow.subtract(counter_spb) # Преобразуется первый счетчик
print(counter_moscow)

Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


3) Получение всех элементов

In [47]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']

counter_moscow = Counter(cars_moscow)

iter_cars = counter_moscow.elements()
print(next(iter_cars))
print(*iter_cars)

black
black black black white white yellow yellow yellow


In [49]:
print(dict(counter_moscow))

{'black': 4, 'white': 2, 'yellow': 3}


In [50]:
# most_common()

print(counter_moscow.most_common())
print(counter_moscow.most_common(2))

[('black', 4), ('yellow', 3), ('white', 2)]
[('black', 4), ('yellow', 3)]


#### defaultdict - задает тот тип данных, который должен храниться в словаре по умолчанию, например список

In [52]:
from collections import defaultdict

In [53]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

groups = defaultdict(list)

for student, group in students:
    groups[group].append(student)

#### deque обладает свойствами как стека, так и очереди

In [56]:
from collections import deque

In [57]:
dq = deque()

У deque есть четыре ключевые функции:

- append (добавить элемент в конец дека);
- appendleft (добавить элемент в начало дека);
- pop (удалить и вернуть элемент из конца дека);
- popleft (удалить и вернуть элемент из начала дека).
- extend - добавить в окнец очереди
- extendlrft - добавить в начало очереди


In [58]:
limited = deque(maxlen=3)
print(limited)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)

# удобно для подсчета какого-то параметра в динамике

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)


In [59]:
dq = deque([1,2,3,4,5])
print(dq)
 
dq.reverse()
print(dq)

deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])


In [60]:
dq = deque([1,2,3,4,5])
print(dq)
 
dq.rotate(2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [61]:
dq = deque([1,2,3,4,5])
print(dq)

dq.rotate(-2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])


In [68]:
# упражнение 
from collections import OrderedDict

temps =  [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]

temperature_dict = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))

print(temperature_dict)

OrderedDict([('2001', -2.5), ('2000', -4.4), ('2002', -4.4), ('2003', -9.5)])


#### numpy.linalg

- np.linalg.norm
- np.dot


#### Случайные числа

###### Генерация чисел с плавающей точкой

In [6]:
import numpy as np

np.random.rand() # случайное число с плавающей запятой

np.random.rand() * 100 # рандомное число в диапазоне от 1 до 100

np.random.rand(3, 2)

shape = (2, 3)

np.random.rand(*shape)

np.random.sample((2, 3)) # генерирует случаные числа в диапазоне от 0 до 1, принимает на вход кортеж

np.random.uniform(low=0.0, high=1.0, size=None)

array([[0.29436645, 0.21410319, 0.61382847],
       [0.66605863, 0.00363799, 0.09172117]])

###### Генерация целых чисел

In [9]:
np.random.randint(10, size=(2,5))

np.random.randint(low=3, high=20, size=(3,4), dtype=int)

array([[15, 16, 10, 18],
       [13, 18, 14,  5],
       [ 9,  8, 10,  6]])

In [17]:
array = np.arange(20)
print(array)
np.random.shuffle(array) # перемешивает чсила в массиве
print(array)

array_2 = np.arange(30)
new_array = np.random.permutation(array_2) # создает новый массив с перемешанными значениями

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[16 19 15  2  4  6  3 11  0  1  9  8 10  5 13 18 17  7 14 12]


In [19]:
np.random.choice([2, 2, 5, 23, 66, 4], size=(2,3), replace=True) # генерация случайного набора объектов из массивва

array([[66,  4, 23],
       [ 4,  5, 66]])

#### seed генератор псевдослучайных чисел

In [25]:
np.random.seed(20)

print(np.random.randint(10, 20, size=(2, 100)))

[[13 19 14 16 17 12 10 16 18 15 13 10 16 16 10 19 15 17 15 12 16 19 13 13
  19 10 16 12 13 11 18 10 12 17 16 16 18 12 11 13 12 16 19 14 16 14 18 16
  12 13 11 15 12 11 18 12 14 14 18 16 10 13 14 10 15 16 19 17 14 10 16 11
  19 16 17 19 17 16 19 18 18 12 12 11 15 12 19 17 15 15 19 16 19 19 15 12
  19 16 11 18]
 [11 10 18 15 10 16 15 14 12 19 19 14 15 13 19 17 11 12 13 16 15 14 14 11
  18 17 11 19 12 13 14 14 14 19 10 15 14 13 12 17 10 16 12 17 15 17 17 15
  16 11 16 14 16 10 17 12 16 12 13 18 16 11 19 16 10 10 17 19 12 13 17 14
  11 13 12 11 16 19 15 15 16 19 14 12 10 14 18 16 14 16 16 17 19 12 14 13
  10 17 10 14]]


In [25]:
import numpy as np

def get_chess(num:int):
    array = np.zeros((num, num))
    array[1::2, ::2] = 1
    array[::2, 1::2] = 1
    return array


print(get_chess(6))

[[0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


In [ ]:
def shuffle_seed(array:list) -> tuple:
    seed = np.random.randint(0, 2**32)
    np.random.seed(seed)
    return (np.random.permutation(array), seed)

In [36]:
import numpy as np

def min_max_dist(*vectors):
    
    list_ = list()
    
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            list_.append(np.linalg.norm(vectors[i] - vectors[j]))
    
    return (min(list_), max(list_))

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

In [37]:
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
    

True


In [39]:
def get_loto(num:int) -> np.array:
    return np.random.randint(1, 100, size=(num, 5, 5))

array([[[45,  5,  8, 54, 81],
        [81, 41, 22, 53, 75],
        [61, 94,  9, 12, 77],
        [74, 21,  7, 35, 96],
        [ 1, 21,  5, 45, 63]],

       [[42, 84, 79, 48, 41],
        [68, 58, 17, 16, 73],
        [56,  7, 60, 38, 36],
        [40, 29, 73, 68, 83],
        [90, 21, 46, 26, 41]],

       [[91, 32, 60,  2, 64],
        [84,  9, 79, 96,  7],
        [34, 67,  2, 61, 79],
        [15, 75,  2,  5, 13],
        [90, 72, 93, 68, 74]]])